### ISSUE TITLE
The count fails in resource "aws_route" "requestor" 

### ISSUE THREAD

**Issue by Sivan-del** [clouddrove/terraform-aws-vpc-peering#9]
The Terraform AWS VPC Peering module fails if the requestor VPC does not exist yet.
We are trying to create the requestor's VPC and the peering at the same time, which ends up in this error:

Error: Invalid count argument

  on .terraform/modules/vpc.vpc_peering/main.tf line 62, in resource "aws_route" "requestor":
  62:   count                     = var.enabled ? length(distinct(sort(data.aws_route_tables.requestor.0.ids))) * length(data.aws_vpc.acceptor.0.cidr_block_associations) : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

Error: Invalid count argument

  on .terraform/modules/vpc.vpc_peering/main.tf line 71, in resource "aws_route" "acceptor":
  71:   count                     = var.enabled ? length(distinct(sort(data.aws_route_tables.acceptor.0.ids))) * length(data.aws_vpc.requestor.0.cidr_block_associations) : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

**Comment by sohanyadav** [comment]
@Sivan-del  looks like an issue with the count of route tables, did you create the route tables and attached them with subnets?
